In [1]:
import pandas as pd
import numpy as np

In [21]:
df_raw = pd.read_table('data/JamesBondGlucoseLevels25.txt',
                       )
df_raw.head()

,ID,Time,Type,hist.glucose.mg.dL.,Scan.glucose.mg.dL.,Not.numeric.fast.insuline,fast.insuline.unit.,Non.numeric.food,carbonhydrates.gram.,Non.numeric.long.insuline,long.insuline.unit.,Remarks,Strip.glucose.mg.dL.,Keton.mmol.L.,meal.insuline.unit.,Correctioninsuline.unit.,userchange.insuline.unit.,previous.time,adjusted.time
561,2845,2019-04-25 00:08,1,NaN,109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
562,2850,2019-04-25 00:50,1,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
563,2877,2019-04-25 07:02,1,NaN,123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
564,2881,2019-04-25 07:34,1,NaN,158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
565,2886,2019-04-25 08:19,1,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
## Converting the time column to datetime format
df_raw.Time = pd.to_datetime(df_raw.Time)
df_raw = df_raw.set_index('Time') # Set time as the index; useful for plotting

In [18]:
## Handling the NaNs and space values
df_raw.replace('  ', np.nan, inplace=True)

## Now convert string column to numeric
df_raw['glucose_scan'] = pd.to_numeric(df_raw['Scan.glucose.mg.dL.']) # create new column and put the converted vals into it

In [19]:
df_raw.head()

,ID,Type,hist.glucose.mg.dL.,Scan.glucose.mg.dL.,Not.numeric.fast.insuline,fast.insuline.unit.,Non.numeric.food,carbonhydrates.gram.,Non.numeric.long.insuline,long.insuline.unit.,Remarks,Strip.glucose.mg.dL.,Keton.mmol.L.,meal.insuline.unit.,Correctioninsuline.unit.,userchange.insuline.unit.,previous.time,adjusted.time,glucose_scan
Time,,,,,,,,,,,,,,,,,,,
2019-04-25 00:08:00,2845,1,NaN,109,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.0
2019-04-25 00:50:00,2850,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-04-25 07:02:00,2877,1,NaN,123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,123.0
2019-04-25 07:34:00,2881,1,NaN,158,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158.0
2019-04-25 08:19:00,2886,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
## Put our work in a function

def reformat():
    df = pd.read_table('data/JamesBondGlucoseLevels25.txt')
    df.Time = pd.to_datetime(df.Time)
    df = df.set_index('Time')
    df.replace('  ', np.nan, inplace=True)
    df['glucose_scan'] = pd.to_numeric(df['Scan.glucose.mg.dL.'])
    df.drop('Scan.glucose.mg.dL.', axis=1, inplace=True)

    return df

In [32]:
df = reformat()
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 136 entries, 2019-04-25 00:08:00 to 2019-04-25 23:48:00
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   ID                         136 non-null    uint64
 1   Type                       136 non-null    int64
 2   hist.glucose.mg.dL.        82 non-null     float64
 3   Not.numeric.fast.insuline  0 non-null      float64
 4   fast.insuline.unit.        0 non-null      float64
 5   Non.numeric.food           0 non-null      float64
 6   carbonhydrates.gram.       0 non-null      float64
 7   Non.numeric.long.insuline  0 non-null      float64
 8   long.insuline.unit.        0 non-null      float64
 9   Remarks                    0 non-null      float64
 10  Strip.glucose.mg.dL.       0 non-null      float64
 11  Keton.mmol.L.              0 non-null      float64
 12  meal.insuline.unit.        0 non-null      float64
 13  Correctioninsuline.unit.   0 non-null      float64
 14  userchange.insuline.unit.  0 non-null      float64
 15  previous.time              0 non-null      float64
 16  adjusted.time              0 non-null      float64
 17  glucose_scan               52 non-null     float64
dtypes: float64(16), int64(1), uint64(1)
memory usage: 20.2 KB

In [33]:
## forwards and backwards fill - REALLY dirty interpolation
df.ffill()
# df.bfill

,ID,Type,hist.glucose.mg.dL.,Not.numeric.fast.insuline,fast.insuline.unit.,Non.numeric.food,carbonhydrates.gram.,Non.numeric.long.insuline,long.insuline.unit.,Remarks,Strip.glucose.mg.dL.,Keton.mmol.L.,meal.insuline.unit.,Correctioninsuline.unit.,userchange.insuline.unit.,previous.time,adjusted.time,glucose_scan
Time,,,,,,,,,,,,,,,,,,
2019-04-25 00:08:00,2845,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.0
2019-04-25 00:50:00,2850,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.0
2019-04-25 07:02:00,2877,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,123.0
2019-04-25 07:34:00,2881,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158.0
2019-04-25 08:19:00,2886,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,158.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-04-25 22:47:00,16143047311250233344,0,108.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.0
2019-04-25 23:02:00,16143047311250233344,0,123.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.0
2019-04-25 23:18:00,16143047311250233344,0,109.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.0
2019-04-25 23:33:00,16143047311250233344,0,108.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.0
2019-04-25 23:48:00,16143047311250233344,0,110.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.0

# Datasets Combineren
- pd.concat: rijen / kolommen aan elkaar plakken
- pd.merge: meer SQL-achtige syntax, meer opties

In [36]:
## Several methods
# pd.concat
# pd.merge
# pd.DataGrame.join

df_01 = pd.DataFrame(np.random.randn(3,5))
df_02 = pd.DataFrame(np.random.randn(3,5))

In [39]:
df_03 = pd.concat([df_01, df_02])
df_03

          0         1         2         3         4
0 -1.382355 -0.437262  0.754945  1.791292 -0.601912
1 -1.231120 -1.190466  1.271679 -0.053357 -1.011686
2  1.266018 -0.759640  0.369960 -0.484782  0.832559
0  0.387034  1.885083  0.416720 -0.260697 -0.783696
1 -0.535782  1.030615 -0.153352 -0.493927  0.680550
2  0.227289  0.532324 -1.083090  0.383089  2.117591

Houd er rekening mee dat .concat hier de indexes onder elkaar plakt; indices hoeven dus niet meer uniek te zijn.
We kunnen ook op kolombasis de tabellen concateneren.

In [40]:
df_04 = np.concat([df_01, df_02], axis=1)
df_04

array([[-1.38235507, -0.43726188,  0.75494473,  1.79129195, -0.60191204,
         0.38703403,  1.88508345,  0.41671956, -0.26069736, -0.78369559],
       [-1.23112026, -1.1904661 ,  1.27167926, -0.05335677, -1.01168602,
        -0.53578185,  1.0306151 , -0.15335239, -0.49392667,  0.68054959],
       [ 1.2660183 , -0.75963989,  0.36996037, -0.48478154,  0.8325589 ,
         0.22728906,  0.53232378, -1.08309012,  0.38308925,  2.11759054]])

In [41]:
A = pd.DataFrame({'key': ['A', 'B', 'C'], 'value' : [1, 2, 3]}).set_index('key')
B = pd.DataFrame({'key': ['A', 'B', 'X', 'Y'], 'value' : [3, 4, 5, 6]}).set_index('key')

In [42]:
A

     value
key
A        1
B        2
C        3

In [43]:
B

     value
key
A        3
B        4
X        5
Y        6

In [44]:
pd.concat([A,B], axis=1)

     value  value
key
A      1.0    3.0
B      2.0    4.0
C      3.0    NaN
X      NaN    5.0
Y      NaN    6.0

### pd.merge

In [45]:
left = pd.DataFrame({'key': ['A', 'B', 'C'], 'left_value' : [1, 2, 3]})
right = pd.DataFrame({'key': ['A', 'B', 'X'], 'right_value' : [3, 4, 5]})

In [49]:
pd.merge(left, right, how='inner', left_on='key', right_on='key')

  key  left_value  right_value
0   A           1            3
1   B           2            4

In [50]:
pd.merge(left, right, how='outer', left_on='key', right_on='key')

  key  left_value  right_value
0   A         1.0          3.0
1   B         2.0          4.0
2   C         3.0          NaN
3   X         NaN          5.0

### Pivot and Melt - dataframes reshapen

In [51]:
data = {
    "value" : range(12),
    "variable" : ['A'] * 3 + ['B'] * 3 + ['C'] * 3 + ['D'] * 3,
    "date" : pd.to_datetime(['2020-01-01', '2020-01-02', '2020-01-03'] * 4),
}

df = pd.DataFrame(data)

In [52]:
df

    value variable       date
0       0        A 2020-01-01
1       1        A 2020-01-02
2       2        A 2020-01-03
3       3        B 2020-01-01
4       4        B 2020-01-02
5       5        B 2020-01-03
6       6        C 2020-01-01
7       7        C 2020-01-02
8       8        C 2020-01-03
9       9        D 2020-01-01
10     10        D 2020-01-02
11     11        D 2020-01-03

Nu willen we 'A', 'B', 'C', 'D' als kolom headers hebben, en de getallen als de waarden in de rows. Dit kun je doen met Pivot.

(long format to wide format)

In [53]:
pivoted = df.pivot(index='date', columns='variable', values='value')
pivoted

variable    A  B  C   D
date
2020-01-01  0  3  6   9
2020-01-02  1  4  7  10
2020-01-03  2  5  8  11

In [55]:
## Wat als ik meer kolommen heb?
df['value2'] = df['value'] * 2
df['value3'] = df['value'] * 3
df

    value variable       date  value2  value3
0       0        A 2020-01-01       0       0
1       1        A 2020-01-02       2       3
2       2        A 2020-01-03       4       6
3       3        B 2020-01-01       6       9
4       4        B 2020-01-02       8      12
5       5        B 2020-01-03      10      15
6       6        C 2020-01-01      12      18
7       7        C 2020-01-02      14      21
8       8        C 2020-01-03      16      24
9       9        D 2020-01-01      18      27
10     10        D 2020-01-02      20      30
11     11        D 2020-01-03      22      33

In [58]:
hierarchical_table = df.pivot(index='date', columns='variable')
hierarchical_table

           value           value2             value3
variable       A  B  C   D      A   B   C   D      A   B   C   D
date
2020-01-01     0  3  6   9      0   6  12  18      0   9  18  27
2020-01-02     1  4  7  10      2   8  14  20      3  12  21  30
2020-01-03     2  5  8  11      4  10  16  22      6  15  24  33

In [62]:
## Access it again:
hierarchical_table['value2']

variable    A   B   C   D
date
2020-01-01  0   6  12  18
2020-01-02  2   8  14  20
2020-01-03  4  10  16  22

Melt is het omgekeerde: gaat van een wide-format naar een long-format.

In [63]:
data = pd.DataFrame({
    'first' : ['John', 'Mary', 'Ben', 'Joe'],
    'last' : ['Doe', 'Jane', 'Wilkinson', 'Roegan'],
    'height' : [160, 183, 179, 181],
    'weight' : [85, 70, 81, 79],
    'other' : [2, 4, 0, 1]
})
data

  first       last  height  weight  other
0  John        Doe     160      85      2
1  Mary       Jane     183      70      4
2   Ben  Wilkinson     179      81      0
3   Joe     Roegan     181      79      1

In [64]:
data.melt(id_vars=['first', 'last'])

   first       last variable  value
0   John        Doe   height    160
1   Mary       Jane   height    183
2    Ben  Wilkinson   height    179
3    Joe     Roegan   height    181
4   John        Doe   weight     85
5   Mary       Jane   weight     70
6    Ben  Wilkinson   weight     81
7    Joe     Roegan   weight     79
8   John        Doe    other      2
9   Mary       Jane    other      4
10   Ben  Wilkinson    other      0
11   Joe     Roegan    other      1

Natuurlijk is deze nieuwe tabel absoluut niet tidy data.